repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: charts/
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.3
    hooks:
      - id: ruff
        args: [--fix]
        additional_dependencies: ["ruff[lint]==0.3.3"]

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy src orchestrator tests
        language: system
        types: [python]
        args: ["--strict"]
        require_serial: true
        pass_filenames: false

      - id: pytest
        name: pytest
        entry: python -m pytest
        language: system
        types: [python]
        args: ["-q"]
        pass_filenames: false
        stages: [manual, pre-push]
