site_name: AI Code Assistant
site_description: FastAPI-based AI code assistant with GPU-aware routing
site_author: crothmeier
repo_url: https://github.com/crothmeier/ai-code-assistant
repo_name: crothmeier/ai-code-assistant

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - tables
  - attr_list
  - md_in_html

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src, orchestrator]
          options:
            show_source: true
            show_root_heading: true
            heading_level: 2

nav:
  - Home: index.md
  - Router Design: router.md
  - Security: security.md
  - Architecture: architecture.md
  - Setup:
    - GitHub Pages: github-pages-setup.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/crothmeier/ai-code-assistant
