{{- define "app.container.name" -}}
{{ .Chart.Name }}-{{ .Values.name | default "app" }}-{{ .Release.Name }}
{{- end -}}

containers:
- name: {{ include "app.container.name" . }}
  image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
  securityContext:
    capabilities:
      drop: [ALL]        # 'ALL' already removes CAP_SYS_ADMIN
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    runAsNonRoot: true