name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  integration-test:
    runs-on: ubuntu-latest
    needs: container-scan
    steps:
      - uses: actions/checkout@v3

      - name: Set up KinD
        uses: engineerd/setup-kind@v0.5.0

      - name: Deploy orchestrator
        run: |
          kubectl apply -f k8s/orchestrator-deployment.yaml
          kubectl rollout status deployment/orchestrator --timeout=180s

      - name: Smoke test
        run: |
          kubectl port-forward svc/orchestrator 8000:8000 &
          PF_PID=$!
          sleep 5
          curl -sf http://localhost:8000/health | grep -q '"status":"ok"'
          kill $PF_PID
