name: CI
on:
  push:
    branches: [main]
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: "3.11"}
      - run: python -m pip install --quiet --upgrade pip
      - run: pip install --quiet .[dev] pytest pytest-asyncio ruff mypy
      - run: ruff check .
      - run: mypy src orchestrator tests --strict --ignore-missing-imports
      - run: pytest -q

  integration-test:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3

      - name: Set up KinD
        uses: engineerd/setup-kind@v0.5.0

      - name: Deploy orchestrator
        run: |
          kubectl apply -f k8s/orchestrator-deployment.yaml
          kubectl rollout status deployment/orchestrator --timeout=180s

      - name: Smoke test
        run: |
          kubectl port-forward svc/orchestrator 8000:8000 &
          PF_PID=$!
          sleep 5
          curl -sf http://localhost:8000/health | grep -q '"status":"ok"'
          kill $PF_PID
